dino:
  head_n_prototypes: 131072
  head_bottleneck_dim: 384
  MRL: True
ibot:
  separate_head: true
  head_n_prototypes: 131072
train:
  batch_size_per_gpu: 32
  dataset_path: LAION:root=$DSDIR/LAION-COCO
  centering: sinkhorn_knopp
  use_block_masking: True
  use_inverse_block: True
  roll: True
  high_resolution_finetune: False
student:
  arch: vit_giant2
  patch_size: 14
  drop_path_rate: 0.4
  ffn_layer: swiglufused
  block_chunks: 4
teacher:
  momentum_teacher: 0.994
optim:
  epochs: 500
  weight_decay_end: 0.2
  base_lr: 2.0e-04  # learning rate for a batch size of 1024
  warmup_epochs: 80
  layerwise_decay: 1.0
crops:
  global_crops_scale:
  - 0.45
  - 1.0
  local_crops_number: 8
  local_crops_scale:
  - 0.05
  - 0.45
  global_crops_size: 224
  local_crops_size: 98
